### ISSUE TITLE
Publish docs on readthedocs.io

### ISSUE THREAD

**Issue by simonschmidt** [thorgate/tg-apicore#4]
Quite simple, ends up looking [like this](http://tg-apicore-test.readthedocs.io/en/latest/):

1. Register on https://readthedocs.io  (can sign in with github but it grants full access to all the things)
1. Import project https://readthedocs.org/dashboard/import/ (can `import manually` using the `https://...` git url to avoid granting access) 
1. If happy to give readthedocs access to all your projects, you are now done, otherwise:
1. Click `admin -> Integrations -> Github....`
1. [Add the webhook url to this project](http://docs.readthedocs.io/en/latest/webhooks.html#github)

**Comment by rivol** [comment]
Done, thanks for the push!

https://tg-apicore.readthedocs.io/en/latest/?badge=latest
